// <auto-generated />
using System;
using BookingPetProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booking_Pet_Project.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251116120246_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BookingPetProject.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MasterClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MasterClassId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookingPetProject.Models.MasterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeEvent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MasterClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10,
                            DateTimeEvent = new DateTime(2025, 12, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intro to painting for beginners",
                            Name = "Painting Basics"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 8,
                            DateTimeEvent = new DateTime(2025, 12, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn to cook simple dishes",
                            Name = "Cooking Workshop"
                        });
                });

            modelBuilder.Entity("BookingPetProject.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Email = "admin@site.com",
                            Name = "Admin",
                            Password = "1234",
                            Role = "admin"
                        },
                        new
                        {
                            Id = "2",
                            Email = "user@site.com",
                            Name = "User",
                            Password = "1234",
                            Role = "user"
                        });
                });

            modelBuilder.Entity("BookingPetProject.Models.Booking", b =>
                {
                    b.HasOne("BookingPetProject.Models.MasterClass", "MasterClass")
                        .WithMany("Bookings")
                        .HasForeignKey("MasterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingPetProject.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MasterClass");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingPetProject.Models.MasterClass", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BookingPetProject.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
